import 'package:args/command_runner.dart';
import 'package:file/file.dart';
import 'package:yaml/yaml.dart';

import '../util/logger.dart';

class InitCommand extends Command<int> {
  InitCommand({required this.fileSystem, required this.logger}) {
    argParser
      ..addOption(
        'name',
        help: "Override the app name (defaults to pubspec.yaml's name).",
      )
      ..addOption(
        'identifier',
        help:
            'Override the bundle/application identifier '
            '(defaults to com.example.<name>).',
      )
      ..addOption(
        'path',
        help:
            'The Flutter project root to scaffold flupo.yaml into '
            '(defaults to the current directory).',
      )
      ..addFlag(
        'force',
        abbr: 'f',
        negatable: false,
        help: 'Overwrite an existing flupo.yaml.',
      );
  }

  final FileSystem fileSystem;
  final Logger logger;

  @override
  String get name => 'init';

  @override
  String get description =>
      'Scaffolds a flupo.yaml manifest inside an existing Flutter project.';

  @override
  Future<int> run() async {
    final results = argResults!;
    final rawPath = results.option('path');
    final projectDir = rawPath == null
        ? fileSystem.currentDirectory
        : fileSystem.directory(
            fileSystem.path.normalize(fileSystem.path.absolute(rawPath)),
          );

    final pubspecFile = projectDir.childFile('pubspec.yaml');
    if (!await pubspecFile.exists()) {
      logger.error(
        'No pubspec.yaml found at ${pubspecFile.path}.\n'
        'Run `flupo init` from inside a Flutter project, or pass --path.',
      );
      return 1;
    }

    final YamlMap pubspec;
    try {
      final loaded = loadYaml(await pubspecFile.readAsString());
      if (loaded is! YamlMap) throw const FormatException('not a mapping');
      pubspec = loaded;
    } on YamlException catch (e) {
      logger.error('Could not parse ${pubspecFile.path}: ${e.message}');
      return 1;
    }

    if (!_looksLikeFlutterProject(pubspec)) {
      logger.error(
        '${pubspecFile.path} does not look like a Flutter project '
        '(no flutter SDK dependency found).\nRun `flutter create .` first.',
      );
      return 1;
    }

    final name = results.option('name') ?? pubspec['name'] as String?;
    if (name == null || name.isEmpty) {
      logger.error(
        'Could not determine an app name. Pass --name, or add "name" to pubspec.yaml.',
      );
      return 1;
    }

    final version = pubspec['version'] as String? ?? '1.0.0+1';
    final identifier = results.option('identifier') ?? 'com.example.$name';

    final manifestFile = projectDir.childFile('flupo.yaml');
    if (await manifestFile.exists() && !results.flag('force')) {
      logger.error(
        '${manifestFile.path} already exists. Pass --force to overwrite it.',
      );
      return 1;
    }

    await manifestFile.writeAsString(
      _renderManifest(name: name, version: version, identifier: identifier),
    );
    logger.info('Wrote ${manifestFile.path}');
    return 0;
  }

  bool _looksLikeFlutterProject(YamlMap pubspec) {
    final dependencies = pubspec['dependencies'];
    if (dependencies is! YamlMap) return false;
    final flutterDep = dependencies['flutter'];
    return flutterDep is YamlMap && flutterDep['sdk'] == 'flutter';
  }

  String _renderManifest({
    required String name,
    required String version,
    required String identifier,
  }) {
    return '''
# flupo.yaml — generated by `flupo init`.

name: $name
version: $version
identifier: $identifier

# Permissions flupo patch wires into AndroidManifest.xml / Info.plist, e.g.:
# permissions:
#   camera: "Need camera access for profile photo"
#   location: "Need location for delivery tracking"
permissions: {}

# Where `flupo build` sends your project to compile.
build:
  target: apk
  runner: github_actions
''';
  }
}
