import 'package:file/memory.dart';
import 'package:flupo/src/command_runner.dart';
import 'package:test/test.dart';

import '../support/mocks.dart';
import '../support/recording_logger.dart';

void main() {
  late MemoryFileSystem fileSystem;
  late RecordingLogger logger;

  setUp(() {
    fileSystem = MemoryFileSystem();
    logger = RecordingLogger();
    fileSystem.directory('/project').createSync(recursive: true);
    fileSystem.currentDirectory = '/project';
  });

  FlupoCommandRunner buildRunner() => FlupoCommandRunner(
    fileSystem: fileSystem,
    processManager: MockProcessManager(),
    logger: logger,
  );

  void writeManifest() {
    fileSystem.file('/project/flupo.yaml')
      ..createSync(recursive: true)
      ..writeAsStringSync('''
# flupo.yaml — generated by `flupo init`.

name: my_app
version: 1.0.0+1
identifier: com.example.my_app

# Permissions comment block.
permissions:
  camera: "Need camera access for profile photo"

# Build comment block.
build:
  target: apk
  runner: github_actions
''');
  }

  String readManifest() =>
      fileSystem.file('/project/flupo.yaml').readAsStringSync();

  group('get', () {
    test('prints the value of an existing scalar key', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'get',
        'build.target',
      ]);

      expect(code, 0);
      expect(logger.infos, ['apk']);
    });

    test('reports a nested key that is not set', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'get',
        'build.github.repo',
      ]);

      expect(code, 0);
      expect(logger.infos, ['build.github.repo is not set.']);
    });

    test('fails cleanly when flupo.yaml is missing', () async {
      final code = await buildRunner().runFlupo([
        'config',
        'get',
        'identifier',
      ]);

      expect(code, 1);
      expect(logger.errors, anyElement(contains('Run `flupo init` first')));
    });

    test('is a usage error with the wrong number of arguments', () async {
      writeManifest();
      final code = await buildRunner().runFlupo(['config', 'get']);

      expect(code, 64);
    });
  });

  group('set', () {
    test('updates an existing scalar key, preserving comments', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'set',
        'build.target',
        'appbundle',
      ]);

      expect(code, 0);
      final content = readManifest();
      expect(content, contains('target: appbundle'));
      expect(content, contains('# Build comment block.'));
      expect(content, contains('name: my_app'));
      expect(content, contains('identifier: com.example.my_app'));
    });

    test('creates missing intermediate maps in block style', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'set',
        'build.github.repo',
        'acme/app',
      ]);

      expect(code, 0);
      expect(readManifest(), contains('  github:\n    repo: acme/app'));
      expect(readManifest(), isNot(contains('{repo:')));
    });

    test(
      'rejects a value that would make the manifest invalid, without writing',
      () async {
        writeManifest();
        final before = readManifest();

        final code = await buildRunner().runFlupo([
          'config',
          'set',
          'build.target',
          'not-a-real-target',
        ]);

        expect(code, 1);
        expect(logger.errors, anyElement(contains('Unsupported build target')));
        expect(readManifest(), before);
      },
    );

    test('rejects an unknown key', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'set',
        'foo.bar',
        'baz',
      ]);

      expect(code, 1);
      expect(
        logger.errors,
        anyElement(contains('Unknown config key "foo.bar"')),
      );
    });

    test('accepts a known permission key', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'set',
        'permissions.location',
        'Need location for delivery tracking',
      ]);

      expect(code, 0);
      expect(
        readManifest(),
        contains('location: Need location for delivery tracking'),
      );
    });

    test('is a usage error with the wrong number of arguments', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'set',
        'build.target',
      ]);

      expect(code, 64);
    });
  });

  group('unset', () {
    test('removes an existing key', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'unset',
        'permissions.camera',
      ]);

      expect(code, 0);
      expect(readManifest(), isNot(contains('camera:')));
    });

    test('is a no-op when the key is already absent', () async {
      writeManifest();
      final code = await buildRunner().runFlupo([
        'config',
        'unset',
        'build.github.repo',
      ]);

      expect(code, 0);
      expect(logger.infos, ['build.github.repo is already not set.']);
    });

    test('refuses to remove a required field, without writing', () async {
      writeManifest();
      final before = readManifest();

      final code = await buildRunner().runFlupo([
        'config',
        'unset',
        'identifier',
      ]);

      expect(code, 1);
      expect(logger.errors, anyElement(contains('is required')));
      expect(readManifest(), before);
    });

    test('rejects an unknown key', () async {
      writeManifest();
      final code = await buildRunner().runFlupo(['config', 'unset', 'foo.bar']);

      expect(code, 1);
      expect(
        logger.errors,
        anyElement(contains('Unknown config key "foo.bar"')),
      );
    });
  });
}
